import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const mainSource = readFileSync('src/main/index.ts', 'utf8')
const preloadSource = readFileSync('src/preload/index.ts', 'utf8')
const preloadBuilderSource = readFileSync('scripts/write-preload-cjs.cjs', 'utf8')
const appSource = readFileSync('src/renderer/App.vue', 'utf8')
const stylesSource = readFileSync('src/renderer/styles.css', 'utf8')

function numericProperty(source: string, property: string): number {
  const match = source.match(new RegExp(`${property}:\\s*(\\d+)`))
  if (!match) {
    throw new Error(`Missing numeric property: ${property}`)
  }

  return Number(match[1])
}

function mainWindowNumericProperty(source: string, property: string): number {
  const match = source.match(new RegExp(`mainWindow = new BrowserWindow\\(\\{[\\s\\S]*?${property}:\\s*(\\d+)`))
  if (!match) {
    throw new Error(`Missing main window numeric property: ${property}`)
  }

  return Number(match[1])
}

function selectorNumericProperty(source: string, selector: string, property: string): number {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = source.match(new RegExp(`${escapedSelector}\\s*\\{[^}]*${property}:\\s*(\\d+)`, 's'))
  if (!match) {
    throw new Error(`Missing ${property} for selector: ${selector}`)
  }

  return Number(match[1])
}

function selectorBlock(source: string, selector: string): string {
  const escapedSelector = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = source.match(new RegExp(`${escapedSelector}\\s*\\{[^}]*\\}`, 's'))
  if (!match) {
    throw new Error(`Missing selector: ${selector}`)
  }

  return match[0]
}

describe('desktop sizing', () => {
  it('keeps the main window spacious and resizable', () => {
    expect(mainWindowNumericProperty(mainSource, 'width')).toBeGreaterThanOrEqual(900)
    expect(mainWindowNumericProperty(mainSource, 'height')).toBeGreaterThanOrEqual(760)
    expect(mainSource).toContain('minWidth: 980')
    expect(mainSource).toContain('minHeight: 820')
    expect(mainSource).toContain('resizable: true')
    expect(mainSource).toContain('frame: false')
    expect(mainSource).toContain('transparent: true')
    expect(mainSource).toContain("backgroundColor: '#00000000'")
  })

  it('renders the main view as a dark reference-style quota dashboard', () => {
    expect(appSource).toContain('dashboard-panel')
    expect(appSource).toContain('dashboard-status-strip')
    expect(appSource).toContain('dashboard-section-label')
    expect(appSource).not.toContain('dashboard-view-tabs')
    expect(appSource).not.toContain('activeDashboardView')
    expect(appSource).toContain('refreshDashboardData')
    expect(appSource).toContain('quota-dial-grid')
    expect(appSource).toContain('quota-dial-card')
    expect(appSource).toContain('quota-dial')
    expect(appSource).toContain('quotaDialStyle')
    expect(appSource).toContain('dashboard-control-strip')
    expect(appSource).toContain('cloudKeyGenerating')
    expect(appSource).toContain('cloudDashboardOpening')
    expect(appSource).toContain("cloudDialogVisible.value = true\n  if (!window.codexMeter) return")
    expect(appSource).toContain('window-control-strip')
    expect(appSource).toContain('window-control-button')
    expect(appSource).toContain('minimizeMainWindow')
    expect(appSource).toContain('closeMainWindow')
    expect(appSource).toContain('widget-control-button')
    expect(appSource).toContain('link-status-pill')
    expect(appSource).toContain('reset-card-list')
    expect(appSource).toContain('reset-card-list-head')
    expect(appSource).toContain('reset-card-row')
    expect(appSource).toContain('resetCards.slice(0, 3)')
    expect(appSource).toContain('resetCardCompactExpiryText')
    expect(appSource).toContain('resetCards.length')
    expect(appSource).toContain('可提前重置额度窗口')
    expect(appSource.indexOf('quota-dial-grid')).toBeLessThan(appSource.indexOf('usage-analytics-panel'))
    expect(appSource).toContain('usage-analytics-panel')
    expect(appSource).toContain('usage-period-grid')
    expect(appSource).toContain('usage-split-strip')
    expect(appSource).toContain('usage-insight-card')
    expect(appSource).toContain('usage-trend-svg')
    expect(appSource).toContain('usage-trend-days')
    expect(appSource).toContain('usage-daily-projects')
    expect(appSource).toContain('selectedUsageDate')
    expect(appSource).toContain('dailyUsageSeries')
    expect(appSource).toContain('usage-rank-grid')
    expect(appSource).toContain('usage-task-board')
    expect(appSource).toContain("label: '输入'")
    expect(appSource).toContain("label: '缓存'")
    expect(appSource).toContain("label: '输出'")
    expect(appSource).toContain('亿`')
    expect(appSource).toContain('百万`')
    expect(appSource).toContain('万`')
    expect(appSource).toContain('getUsageSummary')
    expect(mainSource).toContain("ipcMain.handle('usage:summary'")
    expect(preloadSource).toContain('getUsageSummary')
    expect(preloadBuilderSource).toContain('getUsageSummary')
    expect(appSource).not.toContain('reset-card-grid')
    expect(appSource).not.toContain('reset-card-tile')
    expect(appSource).not.toContain('reset-strip')
    expect(appSource).not.toContain('desktop-hero')
    expect(appSource).not.toContain('usage-section')
    expect(appSource).not.toContain('connection-strip')
    expect(appSource).not.toContain('NProgress')
    expect(stylesSource).toContain('#07111f')
    expect(stylesSource).toContain('conic-gradient')
    expect(selectorBlock(stylesSource, '.dashboard-panel')).toContain('width: 100%')
    expect(selectorBlock(stylesSource, '.dashboard-panel')).toContain('height: 100%')
    expect(selectorBlock(stylesSource, '.desktop-shell')).toContain('-webkit-app-region: no-drag')
    expect(selectorBlock(stylesSource, '.dashboard-header')).toContain('-webkit-app-region: drag')
    expect(selectorNumericProperty(stylesSource, '.dashboard-panel', 'border-radius')).toBeLessThanOrEqual(20)
    expect(selectorNumericProperty(stylesSource, '.window-control-button', 'width')).toBeLessThanOrEqual(30)
    expect(selectorNumericProperty(stylesSource, '.window-control-button', 'height')).toBeLessThanOrEqual(30)
    expect(selectorNumericProperty(stylesSource, '.dashboard-control-strip', 'height')).toBeGreaterThanOrEqual(46)
    expect(selectorBlock(stylesSource, '.hardware-connect-backdrop')).toContain('-webkit-app-region: no-drag')
    expect(selectorBlock(stylesSource, '.quota-dial-grid')).toContain('repeat(3')
    expect(selectorNumericProperty(stylesSource, '.quota-dial-card', 'height')).toBeGreaterThanOrEqual(170)
    expect(selectorNumericProperty(stylesSource, '.quota-dial', 'width')).toBeGreaterThanOrEqual(96)
    expect(selectorNumericProperty(stylesSource, '.reset-card-list', 'height')).toBeGreaterThanOrEqual(170)
    expect(selectorNumericProperty(stylesSource, '.usage-analytics-panel', 'margin-top')).toBeLessThanOrEqual(16)
    expect(selectorNumericProperty(stylesSource, '.usage-insight-tabs', 'height')).toBeGreaterThanOrEqual(28)
    expect(appSource).toContain('usage-reconciliation-layout')
    expect(appSource).toContain('usage-reconciliation-table')
    expect(appSource).toContain("activeUsageInsight = 'reconciliation'")
    expect(mainSource).toContain('fetchOfficialAccountUsage')
  })

  it('starts the widget as a compact floating ball', () => {
    expect(mainSource).toContain('WIDGET_COLLAPSED_SIZE')
    expect(mainSource).toContain('const WIDGET_COLLAPSED_SIZE = { width: 68, height: 68 }')
    expect(selectorNumericProperty(stylesSource, '.widget-shell.is-collapsed', 'width')).toBeLessThanOrEqual(68)
    expect(selectorNumericProperty(stylesSource, '.widget-orb', 'width')).toBe(56)
    expect(appSource).toContain('widget-orb-meter')
    expect(appSource).toContain('widget-orb-gauge')
    expect(appSource).toContain('widget-orb-value')
    expect(appSource).toContain('widget-orb-label')
    expect(appSource).toContain('widgetOrbStyle')
    expect(appSource).toContain('5H')
    expect(appSource).not.toContain('widget-orb-progress')
    expect(appSource).not.toContain('widget-progress-arc is-weekly')
    expect(appSource).not.toContain('widget-liquid-window')
    expect(appSource).not.toContain('widget-liquid-fill')
    expect(appSource).not.toContain('widget-wave-path')
    expect(appSource).not.toContain('widget-bubble')
    expect(appSource).not.toContain('widget-week-label')
    expect(appSource).not.toContain('widget-orb-mark')
    expect(appSource).not.toContain('widget-orb-primary')
    expect(appSource).not.toContain('widget-badge-meta')
    expect(appSource).not.toContain('widget-badge-refresh')
    expect(stylesSource).toContain('.widget-orb::before')
    expect(stylesSource).toContain('backdrop-filter: blur(20px)')
    expect(selectorNumericProperty(stylesSource, '.widget-orb-value', 'font-size')).toBeGreaterThanOrEqual(16)
    expect(selectorNumericProperty(stylesSource, '.widget-orb-value', 'font-size')).toBeLessThanOrEqual(18)
    expect(selectorNumericProperty(stylesSource, '.widget-orb-label', 'font-size')).toBeLessThanOrEqual(9)
    expect(stylesSource).toContain('--widget-five-ring')
    expect(stylesSource).toContain('conic-gradient')
    expect(stylesSource).toContain('#00bfa5')
    expect(selectorBlock(stylesSource, '.widget-orb::before')).not.toContain('filter: blur')
    expect(stylesSource).not.toContain('#7c4dff')
    expect(stylesSource).not.toContain('#a984f5')
    expect(stylesSource).not.toContain('#9a73ef')
    expect(stylesSource).not.toContain('#936be7')
    expect(stylesSource).not.toContain('#df8af7')
    expect(stylesSource).not.toContain('.widget-orb::after')
    expect(stylesSource).not.toContain('widget-liquid-window')
    expect(stylesSource).not.toContain('widget-wave-move')
    expect(stylesSource).not.toContain('widget-bubble-rise')
    expect(stylesSource).not.toContain('stroke-dasharray: 100')
    expect(stylesSource).not.toContain('transform: rotate(-90deg)')
  })

  it('keeps hover details lightweight without expanding the widget window', () => {
    expect(mainSource).not.toContain('WIDGET_EXPANDED_SIZE')
    expect(mainSource).not.toContain("ipcMain.handle('widget:setExpanded'")
    expect(preloadSource).not.toContain('setWidgetExpanded')
    expect(preloadBuilderSource).not.toContain('setWidgetExpanded')
    expect(appSource).toContain('widgetTooltip')
    expect(appSource).toContain(':title="widgetTooltip"')
    expect(appSource).toContain('5 小时剩余')
    expect(appSource).toContain('一周剩余')
    expect(appSource).toContain('重置卡 ${index + 1}')
    expect(appSource).not.toContain('widget-peek')
  })

  it('opens the main window when the floating ball is double-clicked', () => {
    expect(mainSource).toContain("ipcMain.handle('widget:openMainWindow'")
    expect(mainSource).toContain('showMainWindow')
    expect(preloadSource).toContain('openMainWindow')
    expect(preloadBuilderSource).toContain('openMainWindow')
    expect(appSource).toContain('openMainFromWidget')
    expect(appSource).toContain('@dblclick="openMainFromWidget"')
    expect(appSource).not.toContain('handleWidgetOrbClick')
  })

  it('wires frameless main-window controls to the host window', () => {
    expect(mainSource).toContain("ipcMain.handle('window:minimizeMain'")
    expect(mainSource).toContain('mainWindow?.minimize()')
    expect(mainSource).toContain("ipcMain.handle('window:closeMain'")
    expect(mainSource).toContain('mainWindow?.close()')
    expect(preloadSource).toContain('minimizeMainWindow')
    expect(preloadSource).toContain('closeMainWindow')
    expect(preloadBuilderSource).toContain('minimizeMainWindow')
    expect(preloadBuilderSource).toContain('closeMainWindow')
  })

})
